import crypto from 'node:crypto';
import path from 'node:path';
import fs from 'node:fs';

export class GitOpsSerializer {
  // Convert Prompt to Markdown with YAML frontmatter
  static serializePrompt(prompt) {
    const vars = (prompt.variables || []).map(v => `  - name: "${v.name}"\n    defaultValue: "${(v.defaultValue || '').replace(/"/g, '\\"')}"\n    description: "${(v.description || '').replace(/"/g, '\\"')}"`).join('\n');
    const tags = (prompt.tags || []).map(t => `  - "${t}"`).join('\n');

    return `---
id: "${prompt.id}"
title: "${(prompt.title || '').replace(/"/g, '\\"')}"
version: "${prompt.version || '1.0.0'}"
model: "${prompt.model || 'claude-3-7-sonnet'}"
temperature: ${prompt.temperature !== undefined ? prompt.temperature : 0.7}
max_tokens: ${prompt.max_tokens || 2048}
category: "prompts"
source_ref: "${prompt.source_ref || ''}"
source_title: "${(prompt.source_title || '').replace(/"/g, '\\"')}"
auto_synced: ${!!prompt.auto_synced}
tags:
${tags || '  - "general"'}
variables:
${vars || '  - name: "INPUT"\n    defaultValue: ""\n    description: "Input text"'}
---

${prompt.template || ''}
`;
  }

  // Parse YAML frontmatter + Markdown body back to Prompt object
  static deserializePrompt(content, defaultId = '') {
    const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
    if (!match) {
      return { id: defaultId, template: content.trim() };
    }

    const yamlBlock = match[1];
    const body = match[2].trim();
    const result = { id: defaultId, template: body, variables: [], tags: [] };

    // Simple robust YAML extractor for prompt fields
    const extractStr = (key) => {
      const m = yamlBlock.match(new RegExp(`^${key}:\\s*"?(.*?)"?$`, 'm'));
      return m ? m[1] : '';
    };
    const extractNum = (key, def = 0) => {
      const m = yamlBlock.match(new RegExp(`^${key}:\\s*([0-9.]+)`, 'm'));
      return m ? parseFloat(m[1]) : def;
    };

    result.id = extractStr('id') || defaultId;
    result.title = extractStr('title') || result.id;
    result.version = extractStr('version') || '1.0.0';
    result.model = extractStr('model') || 'claude-3-7-sonnet';
    result.temperature = extractNum('temperature', 0.7);
    result.max_tokens = extractNum('max_tokens', 2048);
    result.source_ref = extractStr('source_ref');
    result.source_title = extractStr('source_title');

    // Extract tags
    const tagMatches = yamlBlock.match(/tags:\n([\s\S]*?)(?=\n\w+:|$)/);
    if (tagMatches) {
      const tags = tagMatches[1].split('\n')
        .map(l => l.replace(/^\s*-\s*"?(.*?)"?$/, '$1').trim())
        .filter(Boolean);
      if (tags.length) result.tags = tags;
    }

    return result;
  }

  // Convert Skill to SKILL.md
  static serializeSkill(skill) {
    if (skill.content && skill.content.startsWith('---')) {
      return skill.content;
    }
    const tags = (skill.tags || []).map(t => `  - "${t}"`).join('\n');
    return `---
name: ${skill.name}
description: "${(skill.description || '').replace(/"/g, '\\"')}"
version: "${skill.version || '1.0.0'}"
author: "${skill.author || 'System'}"
category: "skills"
source_ref: "${skill.source_ref || ''}"
tags:
${tags || '  - "agent-skill"'}
---

# ${skill.title || skill.name}

${skill.description || ''}

## Usage Instructions
${skill.content || ''}
`;
  }

  // Convert Workflows to JSON
  static serializeWorkflow(wf) {
    return JSON.stringify(wf, null, 2);
  }

  // Convert MCP Servers collection to mcp_config.json
  static serializeMcpConfig(mcpServers) {
    const mcpServersMap = {};
    for (const server of mcpServers) {
      if (server.transport === 'sse') {
        mcpServersMap[server.name] = {
          url: server.endpoint_url || 'http://localhost:8080/sse',
          headers: server.headers || {}
        };
      } else {
        mcpServersMap[server.name] = {
          command: server.command || 'npx',
          args: server.args || [],
          env: server.env || {}
        };
      }
    }
    return JSON.stringify({ mcpServers: mcpServersMap }, null, 2);
  }

  // Convert Rules to AGENTS.md compiled directives
  static serializeRules(rules) {
    let output = `# AGENTS.md — Canonical AI Behavioral & Safety Directives\n\n`;
    output += `> Automatically generated by Prompt Ops Control Tower (artefactory) GitOps Engine.\n`;
    output += `> Last Compiled: ${new Date().toISOString()}\n\n`;

    const sorted = [...rules].sort((a, b) => {
      const order = { CRITICAL: 1, HIGH: 2, MEDIUM: 3, LOW: 4 };
      return (order[a.priority] || 99) - (order[b.priority] || 99);
    });

    for (const rule of sorted) {
      output += `## [${rule.priority || 'STANDARD'}] ${rule.title}\n`;
      if (rule.source_title) output += `*Source: ${rule.source_title}*\n\n`;
      output += `${rule.content || rule.description || ''}\n\n---\n\n`;
    }

    return output;
  }

  // Generate complete manifest.json
  static generateManifest(db) {
    const prompts = db.getCollection('prompts');
    const skills = db.getCollection('skills');
    const workflows = db.getCollection('workflows');
    const mcp = db.getCollection('mcp_servers');
    const rules = db.getCollection('rules');
    const sources = db.getCollection('sources');

    const computeHash = (data) => crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex').slice(0, 12);

    return {
      schema_version: '2.0.0',
      project: 'artefactory-prompt-ops',
      timestamp: new Date().toISOString(),
      counts: {
        sources: sources.length,
        prompts: prompts.length,
        skills: skills.length,
        workflows: workflows.length,
        mcp_servers: mcp.length,
        rules: rules.length
      },
      manifest_hash: computeHash({ prompts, skills, workflows, mcp, rules }),
      artifacts: {
        prompts: prompts.map(p => ({ id: p.id, title: p.title, version: p.version, file: `prompts/${p.id}.md`, hash: computeHash(p) })),
        skills: skills.map(s => ({ id: s.id, name: s.name, version: s.version, file: `skills/${s.name}/SKILL.md`, hash: computeHash(s) })),
        workflows: workflows.map(w => ({ id: w.id, title: w.title, version: w.version, file: `workflows/${w.id}.json`, hash: computeHash(w) })),
        mcp_servers: mcp.map(m => ({ id: m.id, name: m.name, version: m.version, hash: computeHash(m) })),
        rules: rules.map(r => ({ id: r.id, title: r.title, priority: r.priority, hash: computeHash(r) }))
      }
    };
  }
}
