export const canonicalSources = [
  // 1. Спецификации и протоколы (Specs & Protocols)
  {
    id: "src_mcp_spec",
    title: "Anthropic Model Context Protocol (MCP) Specification",
    category: "specs_protocols",
    categoryLabel: "Спецификации и протоколы",
    url: "https://modelcontextprotocol.io",
    repo_url: "https://github.com/modelcontextprotocol",
    author: "Anthropic & MCP Working Group",
    license: "MIT / Open Standard",
    year: "2024-2026",
    tags: ["mcp", "protocol", "tools", "sse", "stdio", "resources", "prompts"],
    tokens_est: 1850,
    excerpt: "Открытый протокол Model Context Protocol (MCP) для безопасного подключения ИИ-ассистентов к локальным файловым системам, базам данных, API и внешним инструментам через транспорты Stdio и SSE.",
    canonical_schema: "JSON-RPC 2.0 (Streamable HTTP / SSE & Stdio)",
    target_registries: ["mcp", "skills"],
    recommended_action: "Register MCP Server"
  },
  {
    id: "src_a2a_protocol",
    title: "Google Agent-to-Agent (A2A) Communication Protocol",
    category: "specs_protocols",
    categoryLabel: "Спецификации и протоколы",
    url: "https://a2a-protocol.org",
    repo_url: "https://github.com/google/a2a-protocol",
    author: "Google DeepMind / Google Cloud",
    license: "Apache 2.0",
    year: "2025-2026",
    tags: ["a2a", "multi-agent", "negotiation", "task-handoff", "delegation"],
    tokens_est: 1420,
    excerpt: "Стандарт меж-агентного взаимодействия и делегирования задач между автономными сущностями с верификацией возможностей и контрактов обмена контекстом.",
    canonical_schema: "A2A Message Envelope Schema v1.1",
    target_registries: ["workflows", "rules"],
    recommended_action: "Create Workflow DAG"
  },
  {
    id: "src_openai_agents_spec",
    title: "OpenAI Agents & Responses API Specification",
    category: "specs_protocols",
    categoryLabel: "Спецификации и протоколы",
    url: "https://platform.openai.com/docs",
    author: "OpenAI",
    license: "Commercial Specification",
    year: "2024-2026",
    tags: ["openai", "agents-api", "tool-calling", "structured-outputs"],
    tokens_est: 1600,
    excerpt: "Спецификация Structured Outputs (json_schema) и Responses API для детерминированного вызова функций и цепочек инструментов.",
    canonical_schema: "OpenAPI 3.1 / JSON Schema Draft 2020-12",
    target_registries: ["prompts", "mcp"],
    recommended_action: "Create Prompt Template"
  },

  // 2. Промпт-инжиниринг (Prompt Engineering & Registry)
  {
    id: "src_anthropic_prompt_eng",
    title: "Anthropic Claude Prompt Engineering & Meta-Prompting Guide",
    category: "prompt_engineering",
    categoryLabel: "Промпт-инжиниринг",
    url: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering",
    author: "Anthropic Alignment & Developer Relations",
    license: "CC-BY-4.0",
    year: "2024-2026",
    tags: ["claude", "prompt-engineering", "xml-tags", "chain-of-thought", "system-prompts"],
    tokens_est: 2400,
    excerpt: "Канонические практики структурирования промптов с использованием XML-тегов (<instructions>, <context>, <examples>), многоэтапных цепочек рассуждений (CoT) и префиллинга ответов.",
    canonical_schema: "XML-tagged Markdown Prompt Structure",
    target_registries: ["prompts", "rules"],
    recommended_action: "Create Prompt Template"
  },
  {
    id: "src_dspy_framework",
    title: "DSPy: Programming—not Prompting—Foundation Models",
    category: "prompt_engineering",
    categoryLabel: "Промпт-инжиниринг",
    url: "https://dspy.ai",
    repo_url: "https://github.com/stanfordnlp/dspy",
    author: "Stanford NLP Group",
    license: "MIT",
    year: "2024-2026",
    tags: ["dspy", "compiled-prompts", "signatures", "teleprompter", "optimization"],
    tokens_est: 2100,
    excerpt: "Фреймворк декларативного программирования промптов: сигнатуры вход-выход, автоматическая оптимизация (Teleprompter) и компиляция цепочек в пайплайны.",
    canonical_schema: "DSPy Signature: InputField -> OutputField",
    target_registries: ["prompts", "workflows"],
    recommended_action: "Create Prompt Template"
  },
  {
    id: "src_promptlayer_registry",
    title: "PromptLayer Prompt Registry Architecture & Semantic Versioning",
    category: "prompt_engineering",
    categoryLabel: "Промпт-инжиниринг",
    url: "https://docs.promptlayer.com/features/prompt-registry/overview",
    author: "PromptLayer Engineering",
    license: "Documentation & Architecture Reference",
    year: "2024-2026",
    tags: ["prompt-registry", "semver", "playground", "observability", "versioning"],
    tokens_est: 1350,
    excerpt: "Архитектурный паттерн реестра промптов: разделение версий на dev/staging/prod, связывание входных переменных, замер стоимости токенов и аудит-трейсинг.",
    canonical_schema: "Prompt Manifest v2.0",
    target_registries: ["prompts", "rules"],
    recommended_action: "Create Prompt Template"
  },

  // 3. Оркестрация агентов (Agent Orchestration)
  {
    id: "src_langgraph",
    title: "LangGraph: Stateful Multi-Agent Cyclic Graph Architecture",
    category: "orchestration",
    categoryLabel: "Оркестрация агентов",
    url: "https://langchain-ai.github.io/langgraph",
    repo_url: "https://github.com/langchain-ai/langgraph",
    author: "LangChain AI",
    license: "MIT",
    year: "2024-2026",
    tags: ["langgraph", "dag", "state-machine", "human-in-the-loop", "multi-agent"],
    tokens_est: 2800,
    excerpt: "Фреймворк построения устойчивых агентных систем на базе графов состояний с циклическими переходами, контрольными точками (checkpoints) и Human-in-the-loop шлюзами.",
    canonical_schema: "StateGraph DAG Definition",
    target_registries: ["workflows", "skills"],
    recommended_action: "Create Workflow DAG"
  },
  {
    id: "src_crewai",
    title: "CrewAI: Role-Playing Autonomous AI Agent Teams",
    category: "orchestration",
    categoryLabel: "Оркестрация агентов",
    url: "https://docs.crewai.com",
    repo_url: "https://github.com/crewAIInc/crewAI",
    author: "CrewAI Inc.",
    license: "MIT",
    year: "2024-2026",
    tags: ["crewai", "multi-agent", "roles", "delegation", "task-execution"],
    tokens_est: 1950,
    excerpt: "Фреймворк оркестрации команд ролевых агентов (Researcher, Writer, Reviewer) с распределением задач, совместной памятью и строгим контролем инструментов.",
    canonical_schema: "Crew YAML Config (Agents + Tasks)",
    target_registries: ["skills", "workflows"],
    recommended_action: "Create Skill"
  },
  {
    id: "src_autogen_ag2",
    title: "AutoGen / AG2: Multi-Agent Conversational Framework",
    category: "orchestration",
    categoryLabel: "Оркестрация агентов",
    url: "https://microsoft.github.io/autogen",
    repo_url: "https://github.com/ag2ai/ag2",
    author: "Microsoft Research & AG2 Community",
    license: "CC-BY-4.0 / MIT",
    year: "2024-2026",
    tags: ["autogen", "ag2", "group-chat", "conversational-agents", "debate"],
    tokens_est: 2200,
    excerpt: "Платформа для диалогового взаимодействия агентов: групповые чаты (GroupChat), дебаты экспертов, автоматическое написание и безопасное выполнение кода.",
    canonical_schema: "ConversableAgent Config",
    target_registries: ["workflows", "skills"],
    recommended_action: "Create Workflow DAG"
  },

  // 4. Наблюдаемость и Eval (Observability & Evaluation)
  {
    id: "src_promptfoo",
    title: "Promptfoo: LLM Evaluation, Red Teaming & CI/CD Security Matrix",
    category: "observability_eval",
    categoryLabel: "Наблюдаемость и Eval",
    url: "https://www.promptfoo.dev/docs",
    repo_url: "https://github.com/promptfoo/promptfoo",
    author: "Promptfoo Open Source",
    license: "MIT",
    year: "2024-2026",
    tags: ["promptfoo", "evals", "red-teaming", "ci-cd", "regression-testing", "scoring"],
    tokens_est: 2300,
    excerpt: "Инструмент для автоматизированного тестирования промптов в CI/CD: ассерты точности, защита от джейлбрейков, матрицы сравнения моделей и замер стоимости/задержки.",
    canonical_schema: "promptfooconfig.yaml",
    target_registries: ["workflows", "rules"],
    recommended_action: "Create Workflow DAG"
  },
  {
    id: "src_langfuse",
    title: "Langfuse: Open Source LLM Engineering & Tracing Platform",
    category: "observability_eval",
    categoryLabel: "Наблюдаемость и Eval",
    url: "https://langfuse.com/docs",
    repo_url: "https://github.com/langfuse/langfuse",
    author: "Langfuse Team",
    license: "MIT",
    year: "2024-2026",
    tags: ["langfuse", "tracing", "token-metrics", "prompt-management", "scores"],
    tokens_est: 1900,
    excerpt: "Платформа трассировки вызовов LLM: сбор логов по сессиям, подсчёт затрат по моделям, версионирование промптов и разметка качества генераций.",
    canonical_schema: "OpenTelemetry GenAI Tracing Schema",
    target_registries: ["prompts", "rules"],
    recommended_action: "Create Rule Directive"
  },

  // 5. Локальный рантайм и инференс (Local Runtimes)
  {
    id: "src_llama_cpp_gguf",
    title: "llama.cpp & GGUF Binary Quantization Format Specification",
    category: "local_runtimes",
    categoryLabel: "Локальный рантайм",
    url: "https://github.com/ggml-org/llama.cpp",
    author: "Georgi Gerganov & GGML Community",
    license: "MIT",
    year: "2024-2026",
    tags: ["llama-cpp", "gguf", "quantization", "cpu-inference", "apple-silicon", "cuda"],
    tokens_est: 2500,
    excerpt: "Высокопроизводительный C/C++ инференс больших языковых моделей на CPU и GPU с поддержкой 2-8 битного квантования GGUF, грамматик вывода (GBNF) и HTTP-сервера.",
    canonical_schema: "GGUF Binary Spec v3 / GBNF Grammars",
    target_registries: ["skills", "mcp"],
    recommended_action: "Create Skill"
  },
  {
    id: "src_ollama_runtime",
    title: "Ollama: Local Large Language Model Runner & API",
    category: "local_runtimes",
    categoryLabel: "Локальный рантайм",
    url: "https://docs.ollama.com",
    repo_url: "https://github.com/ollama/ollama",
    author: "Ollama Team",
    license: "MIT",
    year: "2024-2026",
    tags: ["ollama", "local-llm", "modelfile", "openai-compatible-api", "offline"],
    tokens_est: 1750,
    excerpt: "Универсальный демон запуска локальных моделей (Llama 3, Qwen 2.5, DeepSeek, Mistral) с поддержкой Modelfile, параметров температуры и OpenAI-совместимого REST API.",
    canonical_schema: "Modelfile (FROM, PARAMETER, SYSTEM, TEMPLATE)",
    target_registries: ["mcp", "skills"],
    recommended_action: "Register MCP Server"
  },
  {
    id: "src_vllm_engine",
    title: "vLLM: High-Throughput & Memory-Efficient LLM Serving",
    category: "local_runtimes",
    categoryLabel: "Локальный рантайм",
    url: "https://docs.vllm.ai",
    repo_url: "https://github.com/vllm-project/vllm",
    author: "UC Berkeley & vLLM Project",
    license: "Apache 2.0",
    year: "2024-2026",
    tags: ["vllm", "paged-attention", "high-throughput", "continuous-batching", "gpu"],
    tokens_est: 2150,
    excerpt: "Движок высокопроизводительного серверного инференса с алгоритмом PagedAttention для управления KV-кэшем, continuous batching и многократным ускорением отдачи токенов.",
    canonical_schema: "OpenAI-compatible /v1/chat/completions API",
    target_registries: ["skills", "workflows"],
    recommended_action: "Create Skill"
  },

  // 6. Безопасность и анализ угроз LLM (Security & Threat Models)
  {
    id: "src_owasp_llm_top10",
    title: "OWASP Top 10 for Large Language Model Applications (2025/2026)",
    category: "security_threats",
    categoryLabel: "Безопасность LLM",
    url: "https://genai.owasp.org",
    author: "OWASP GenAI Security Project",
    license: "CC-BY-SA-4.0",
    year: "2025-2026",
    tags: ["owasp", "llm-security", "prompt-injection", "insecure-output", "excessive-agency", "guardrails"],
    tokens_est: 3200,
    excerpt: "Официальный стандарт уязвимостей LLM-приложений: LLM01:2025 Prompt Injection, LLM02: Sensitive Info Disclosure, LLM06: Excessive Agency, LLM07: System Prompt Leakage и методы их нейтрализации.",
    canonical_schema: "OWASP Risk Identification & Mitigation Matrix",
    target_registries: ["rules", "prompts"],
    recommended_action: "Create Rule Directive"
  },
  {
    id: "src_mitre_atlas",
    title: "MITRE ATLAS: Adversarial Threat Landscape for Artificial-Intelligence Systems",
    category: "security_threats",
    categoryLabel: "Безопасность LLM",
    url: "https://atlas.mitre.org",
    author: "MITRE Corporation",
    license: "MITRE Open Access",
    year: "2024-2026",
    tags: ["mitre-atlas", "ai-threats", "reconnaissance", "model-evasion", "data-poisoning"],
    tokens_est: 2700,
    excerpt: "База знаний тактик и техник атак на AI-системы на основе реальных инцидентов: обход гардрайлов, отравление контекста RAG и экфильтрация системных директив.",
    canonical_schema: "ATLAS Tactics & Techniques Matrix",
    target_registries: ["rules", "workflows"],
    recommended_action: "Create Rule Directive"
  },
  {
    id: "src_garak_scanner",
    title: "NVIDIA Garak: LLM Vulnerability & Hallucination Scanner",
    category: "security_threats",
    categoryLabel: "Безопасность LLM",
    url: "https://github.com/NVIDIA/garak",
    author: "NVIDIA AI Security Research",
    license: "Apache 2.0",
    year: "2024-2026",
    tags: ["garak", "security-scanner", "vulnerabilities", "red-teaming", "probes"],
    tokens_est: 1800,
    excerpt: "Автоматизированный сканер уязвимостей нейросетей: генеративные пробы на Prompt Injection, утечку данных, дезинформацию и токсичность.",
    canonical_schema: "Garak Probe & Detector Suite",
    target_registries: ["skills", "workflows"],
    recommended_action: "Create Skill"
  },

  // 7. TUI и Dense UX паттерны (Terminal & Dense UI)
  {
    id: "src_dense_tui_patterns",
    title: "Dense TUI & Modal Command Architecture (Textual / Bubble Tea / Ratatui)",
    category: "tui_ux",
    categoryLabel: "TUI и Dense UX",
    url: "https://ratatui.rs",
    repo_url: "https://github.com/charmbracelet/bubbletea",
    author: "TUI & Modern Terminal Working Group",
    license: "MIT",
    year: "2024-2026",
    tags: ["tui", "dense-ux", "vim-keys", "command-palette", "bubbletea", "ratatui"],
    tokens_est: 1650,
    excerpt: "Паттерны построения высокоплотных интерфейсов управления: модальные режимы, быстрые шорткаты (Cmd+K / :command), компактные таблицы данных и моментальный отклик.",
    canonical_schema: "Dense TUI Layout Grid & Modal Event Model",
    target_registries: ["rules", "skills"],
    recommended_action: "Create Rule Directive"
  },

  // 8. Датасеты промптов и открытые хабы (Datasets & Hubs)
  {
    id: "src_awesome_prompts",
    title: "Awesome ChatGPT Prompts & Structured Persona Repository",
    category: "datasets_hubs",
    categoryLabel: "Датасеты и хабы",
    url: "https://github.com/f/awesome-chatgpt-prompts",
    author: "Fatih Kadir Akın & Open Community",
    license: "CC0-1.0 Public Domain",
    year: "2024-2026",
    tags: ["prompts-dataset", "personas", "system-prompts", "roleplay", "benchmarks"],
    tokens_est: 3100,
    excerpt: "Курируемый открытый датасет системных промптов и ролевых персон (Software Architect, SQL Optimizer, Cyber Security Analyst, Tech Spec Writer) для валидации агентов.",
    canonical_schema: "CSV / JSON Lines Prompts Schema",
    target_registries: ["prompts"],
    recommended_action: "Create Prompt Template"
  },

  // 9. Корпоративный контур и оркестрация (Enterprise & Webhooks)
  {
    id: "src_telegram_n8n_integration",
    title: "Telegram Bot API & n8n Enterprise Workflow Integration",
    category: "enterprise_integrations",
    categoryLabel: "Корпоративный контур",
    url: "https://core.telegram.org/bots/api",
    repo_url: "https://docs.n8n.io",
    author: "Telegram Core & n8n GmbH",
    license: "Open API / Sustainable Use License",
    year: "2024-2026",
    tags: ["telegram-bot", "n8n", "webhooks", "publishing", "event-driven", "bitrix24"],
    tokens_est: 2200,
    excerpt: "Спецификация интеграции автономных агентных систем с корпоративными каналами: публикации в Telegram через Bot API, обработка вебхуков в n8n и CRM-события Bitrix24/1C.",
    canonical_schema: "Telegram Webhook & n8n JSON Workflow Schema",
    target_registries: ["skills", "workflows", "mcp"],
    recommended_action: "Create Skill"
  },

  // 10. Исследования 2024–2026 (Frontier AI Research)
  {
    id: "src_agentic_rag_research",
    title: "Agentic RAG & Multi-Agent Debate Research Papers (2024–2026)",
    category: "frontier_research",
    categoryLabel: "Исследования 2024–2026",
    url: "https://crfm.stanford.edu/helm",
    author: "Stanford CRFM, DeepMind, LMSYS",
    license: "Open Access Research",
    year: "2025-2026",
    tags: ["agentic-rag", "multi-agent-debate", "constitutional-ai", "helm-benchmark", "lmsys"],
    tokens_est: 2900,
    excerpt: "Фундаментальные исследования мультиагентного синтеза: Agentic RAG с итеративной маршрутизацией запросов, Self-Correction, Constitutional AI и методология судейства LLM-as-a-Judge.",
    canonical_schema: "Research Findings & Evaluation Protocol",
    target_registries: ["rules", "workflows"],
    recommended_action: "Create Rule Directive"
  }
];
